# Generated by Django 4.2 on 2024-07-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purcharse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='num_document',
        ),
        migrations.AddField(
            model_name='purchase',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Cambio'),
        ),
    ]
