# Generated by Django 4.2 on 2024-07-22 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purcharse', '0002_remove_purchase_num_document_purchase_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='change',
        ),
    ]
