# Generated by Django 4.2 on 2024-09-21 17:31

import datetime
from django.db import migrations, models
import proy_sales.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_productprice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 21, 17, 31, 10, 338615, tzinfo=datetime.timezone.utc), validators=[proy_sales.utils.validate_expiration_date], verbose_name='Caducidad'),
        ),
    ]
