# Generated by Django 4.2.12 on 2024-07-07 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_created_product_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 23, 52, 23, 831840, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
    ]
