# Generated by Django 4.2.12 on 2024-07-08 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='description',
            field=models.CharField(max_length=100, unique=True, verbose_name='Metodo de Pago'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 7, 16, 19, 22, 324070, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
    ]
