# Generated by Django 4.2.12 on 2024-07-09 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_paymentmethod_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 1, 3, 56, 447742, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
    ]
