# Generated by Django 4.2.12 on 2024-07-10 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_productprice_created_productprice_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 9, 23, 29, 667465, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
    ]
