# Generated by Django 4.2.12 on 2024-07-11 02:11

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='iva',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='iva',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 10, 2, 11, 42, 722327, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
    ]
