# Generated by Django 4.2.12 on 2024-07-11 16:52

import datetime
import django.core.validators
from django.db import migrations, models
import proy_sales.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_iva_created_iva_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='dni',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[proy_sales.utils.valida_cedula], verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='company',
            name='landline',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe ingresarse en el formato: (0X) XXXX-XXXX, donde 0X es el código de área (por ejemplo, 02 para Quito, 04 para Guayaquil).', regex='^\\(0[2-7]\\) \\d{4}-\\d{4}$')], verbose_name='Teléfono Fijo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.URLValidator(message='Por favor, introduce una URL válida.')], verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dni',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[proy_sales.utils.valida_cedula], verbose_name='Dni'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[proy_sales.utils.valida_cedula], verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 10, 16, 52, 10, 232277, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
    ]
