# Generated by Django 4.2.12 on 2024-07-11 17:59

import datetime
import django.core.validators
from django.db import migrations, models
import proy_sales.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_company_dni_alter_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='authorization_number',
            field=models.CharField(blank=True, default='12345678901234567890123456789234567890', help_text='Número de autorización otorgado por el SRI.', max_length=49, null=True, verbose_name='Número de Autorización'),
        ),
        migrations.AlterField(
            model_name='company',
            name='dni',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[proy_sales.utils.valida_ruc], verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='company',
            name='landline',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Formato correcto: (0X) XXXX-XXXX, donde 0X es el código de área.', regex='^\\(0[2-7]\\) \\d{4}-\\d{4}$')], verbose_name='Teléfono Fijo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.URLValidator], verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 10, 17, 59, 14, 947313, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
    ]
