# Generated by Django 4.2.12 on 2024-07-11 19:10

import datetime
from django.db import migrations, models
import proy_sales.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_company_authorization_number_alter_company_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='authorization_number',
            field=models.CharField(blank=True, default=proy_sales.utils.generate_random_authorization_number, help_text='Número de autorización otorgado por el SRI.', max_length=49, null=True, verbose_name='Número de Autorización'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 10, 19, 10, 16, 739005, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
    ]
