# Generated by Django 4.2.12 on 2024-07-12 02:22

import datetime
import django.core.validators
from django.db import migrations, models
import proy_sales.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_company_authorization_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='establishment_code',
            field=models.CharField(blank=True, default=proy_sales.utils.generate_establishment_code, help_text='Código de tres dígitos asignado al establecimiento por el SRI. Para empresas sin sucursales, usar "001".', max_length=3, null=True, unique=True, verbose_name='Código de Establecimiento'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[proy_sales.utils.valida_cedula], verbose_name='Dni'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 11, 2, 22, 19, 109045, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
    ]
