# Generated by Django 4.2.12 on 2024-07-12 05:11

import datetime
import django.core.validators
from django.db import migrations, models
import proy_sales.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_customer_phone_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[proy_sales.utils.validate_date_of_birth], verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe contener entre 9 y 15 dígitos, con un código de país opcional en formato '+XXX '.", regex='^(\\+\\d{1,3}\\s?)?\\d{9,12}$')], verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 11, 5, 11, 12, 102955, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe contener entre 9 y 15 dígitos, con un código de país opcional en formato '+XXX '.", regex='^(\\+\\d{1,3}\\s?)?\\d{9,12}$')], verbose_name='Telefono'),
        ),
    ]
