# Generated by Django 4.2.12 on 2024-07-12 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_customer_date_of_birth_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iva',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6, unique=True, verbose_name='Porcentaje(%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 11, 5, 59, 52, 836419, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
    ]
