# Generated by Django 4.2.12 on 2024-07-12 07:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_line_created_line_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 11, 7, 53, 16, 525103, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
    ]
