# Generated by Django 4.2.12 on 2024-07-12 11:35

import datetime
import django.core.validators
from django.db import migrations, models
import proy_sales.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_product_expiration_date_alter_supplier_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 11, 11, 35, 7, 792668, tzinfo=datetime.timezone.utc), validators=[proy_sales.utils.validate_expiration_date], verbose_name='Caducidad'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe contener entre 9 y 15 dígitos, con un código de país opcional en formato '+XXX '.", regex='^(\\+\\d{1,3}\\s?)?\\d{9,12}$')], verbose_name='Telefono'),
        ),
    ]
