# Generated by Django 4.2.12 on 2024-07-15 23:54

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_product_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='created',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='iva',
            name='created',
        ),
        migrations.RemoveField(
            model_name='iva',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='line',
            name='created',
        ),
        migrations.RemoveField(
            model_name='line',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='created',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='created',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='updated',
        ),
        migrations.AlterField(
            model_name='company',
            name='authorization_number',
            field=models.CharField(blank=True, default='12345678901234567890123456789012345678901234567890', help_text='Número de autorización otorgado por el SRI.', max_length=49, null=True, verbose_name='Número de Autorización'),
        ),
        migrations.AlterField(
            model_name='company',
            name='dni',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='company',
            name='establishment_code',
            field=models.CharField(blank=True, default='001', help_text='Código de tres dígitos asignado al establecimiento por el SRI. Para empresas sin sucursales, usar "001".', max_length=3, null=True, verbose_name='Código de Establecimiento'),
        ),
        migrations.AlterField(
            model_name='company',
            name='landline',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono Fijo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dni',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Dni'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='iva',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Porcentaje(%)'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Metodo de Pago'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10, verbose_name='Costo Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 23, 54, 7, 491153, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='issue_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha Emision'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe contener entre 9 y 15 dígitos, con un código de país opcional en formato '+XXX '.", regex='^(\\+\\d{1,3}\\s?)?\\d{9,12}$')], verbose_name='Telefono'),
        ),
    ]
