# Generated by Django 4.2.12 on 2024-07-15 23:58

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import proy_sales.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_brand_created_remove_brand_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='iva',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='iva',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='line',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='line',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='productprice',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='authorization_number',
            field=models.CharField(blank=True, default=proy_sales.utils.generate_random_authorization_number, help_text='Número de autorización otorgado por el SRI.', max_length=49, null=True, verbose_name='Número de Autorización'),
        ),
        migrations.AlterField(
            model_name='company',
            name='dni',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[proy_sales.utils.valida_ruc], verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='company',
            name='establishment_code',
            field=models.CharField(blank=True, default=proy_sales.utils.generate_establishment_code, help_text='Código de tres dígitos asignado al establecimiento por el SRI. Para empresas sin sucursales, usar "001".', max_length=3, null=True, unique=True, verbose_name='Código de Establecimiento'),
        ),
        migrations.AlterField(
            model_name='company',
            name='landline',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Formato correcto: (0X) XXXX-XXXX, donde 0X es el código de área.', regex='^\\(0[2-7]\\) \\d{4}-\\d{4}$')], verbose_name='Teléfono Fijo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.URLValidator], verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[proy_sales.utils.validate_date_of_birth], verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[proy_sales.utils.valida_cedula], verbose_name='Dni'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe contener entre 9 y 15 dígitos, con un código de país opcional en formato '+XXX '.", regex='^(\\+\\d{1,3}\\s?)?\\d{9,12}$')], verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='iva',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6, unique=True, verbose_name='Porcentaje(%)'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='description',
            field=models.CharField(max_length=100, unique=True, verbose_name='Metodo de Pago'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10, validators=[proy_sales.utils.valida_numero_flotante_positivo], verbose_name='Costo Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 23, 58, 36, 506546, tzinfo=datetime.timezone.utc), validators=[proy_sales.utils.validate_expiration_date], verbose_name='Caducidad'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='issue_date',
            field=models.DateTimeField(db_index=True, validators=[proy_sales.utils.get_current_datetime], verbose_name='Fecha Emision'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe contener entre 9 y 15 dígitos, con un código de país opcional en formato '+XXX '.", regex='^(\\+\\d{1,3}\\s?)?\\d{9,12}$')], verbose_name='Telefono'),
        ),
    ]
