# Generated by Django 4.2.12 on 2024-07-18 05:45

import datetime
from django.db import migrations, models
import proy_sales.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='latitude',
            field=models.CharField(default='0.0', max_length=100, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='company',
            name='longitude',
            field=models.CharField(default='0.0', max_length=100, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 17, 5, 45, 46, 966452, tzinfo=datetime.timezone.utc), validators=[proy_sales.utils.validate_expiration_date], verbose_name='Caducidad'),
        ),
    ]
