# Generated by Django 4.2.12 on 2024-07-16 00:13

import datetime
from django.db import migrations, models
import proy_sales.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='authorization_number',
            field=models.CharField(blank=True, default=proy_sales.utils.generate_random_authorization_number, help_text='Número de autorización otorgado por el SRI.', max_length=55, null=True, verbose_name='Número de Autorización'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 0, 13, 16, 925605, tzinfo=datetime.timezone.utc), validators=[proy_sales.utils.validate_expiration_date], verbose_name='Caducidad'),
        ),
    ]
