# Generated by Django 4.2.12 on 2024-07-18 15:21

import datetime
import django.core.validators
from django.db import migrations, models
import proy_sales.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='landline',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Formato correcto: (0X) XXXX-XXXX, donde 0X es el código de área.', regex='^\\(0[2-7]\\) \\d{4}-\\d{4}$')], verbose_name='Teléfono Fijo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 17, 15, 21, 25, 615044, tzinfo=datetime.timezone.utc), validators=[proy_sales.utils.validate_expiration_date], verbose_name='Caducidad'),
        ),
    ]
