# Generated by Django 4.2.12 on 2024-07-16 00:15

import datetime
from django.db import migrations, models
import proy_sales.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_company_authorization_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='economic_activity_code',
            field=models.CharField(blank=True, default='1234567890', help_text='Código de la actividad económica según el SRI.', max_length=15, null=True, verbose_name='Código de Actividad Económica'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 0, 15, 1, 391781, tzinfo=datetime.timezone.utc), validators=[proy_sales.utils.validate_expiration_date], verbose_name='Caducidad'),
        ),
    ]
