# Generated by Django 4.2.12 on 2024-07-16 00:33

import datetime
from django.db import migrations, models
import proy_sales.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 0, 33, 36, 845928, tzinfo=datetime.timezone.utc), validators=[proy_sales.utils.validate_expiration_date], verbose_name='Caducidad'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='observaciones',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Obervacion'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Incremento'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='ruc',
            field=models.CharField(max_length=13, unique=True, validators=[proy_sales.utils.valida_cedula], verbose_name='Dni'),
        ),
    ]
